### ISSUE TITLE
Add projectUrl to Nuget package

### ISSUE THREAD

**Issue by evest** [Geta/geta-optimizely-genericlinks#12]
The current package has a link to the repository using the `<repository>` tag in the nuspec file, which is not shown on the Optimizely [Nuget package page](https://nuget.optimizely.com/package/?id=Geta.Optimizely.GenericLinks).

If you add the url to the repo in the `<projectUrl>` as well, the package page will link to the "Project Site"

**Comment by svenrog** [comment]
@evest I've added the requested details in the submitted `1.4.4` version of the packages.

**Comment by svenrog** [comment]
Project site is visible on the package pages now.
https://nuget.optimizely.com/package/?id=Geta.Optimizely.GenericLinks and https://nuget.optimizely.com/package/?id=Geta.Optimizely.GenericLinks.ContentDeliveryApi.
