### ISSUE TITLE
Display and functionality issues in quick edit 

### ISSUE THREAD

**Issue by benmurphycb** [Geta/geta-optimizely-genericlinks#13]
Hello,

When a block has a generic link property, the display is not working correctly in the quick edit dialog.

![image](https://user-images.githubusercontent.com/54355060/204516828-1942c3d5-b4c8-4995-a456-abf1f8ae0f52.png)

I think this just needs the main box having a width of `calc(100% - 42px)`.

Functionality:
It seems that the link is added correctly, but when clicking the 3 dots to edit again, the data is missing.

**Comment by svenrog** [comment]
Closed due to inactivity.
