### ISSUE TITLE
Set default value to property

### ISSUE THREAD

**Issue by joemayberry-perficient** [Geta/geta-optimizely-genericlinks#16]
Is there a way to set a default value for a property on a link data model in a LinkDataCollection?

For example, I have a string property in the linkdatamodel that needs to be set for each item with a unique value (in this case a guid).

**Comment by svenrog** [comment]
Currently not possible due to restrictions in the editor. Value would have to be set inside dojo widget. I'm thinking of adding support for [DefaultValue] attributes in version 2.0.
