### ISSUE TITLE
Autosave on cancel clears link property

### ISSUE THREAD

**Issue by joemayberry-perficient** [Geta/geta-optimizely-genericlinks#17]
We are currently running GenericLinks version 1.4.5 with Optimizely CMS version 12.19.0.

We are seeing an issue where editing an existing link, clicking Cancel, will trigger a CMS autosave. If the content is then published, the generic link property will be cleared and all link data lost.

I noticed in the Changelog there is a version 1.5.0 for generic links, but the NuGet feed does only goes to version 1.4.5.

Is this issue addressed in 1.5.0? and if so, when will it be available from NuGet.

Thank you,
Joe Mayberry

**Comment by svenrog** [comment]
This has been addressed in `v1.6.1` and submitted to https://nuget.optimizely.com/
