### ISSUE TITLE
Select content modal is empty

### ISSUE THREAD

**Issue by adayinthelifeofapro** [Geta/geta-optimizely-genericlinks#19]
With the latest version of Umbraco CMS 12.22.1 when you are using a LinkDataCollection, if you choose to "Select Content" rather than "Create a new link" then the modal that appears is showing as empty and no tree-view is showing. This has been tested on a fresh install of the Alloy demo site.

![image](https://github.com/Geta/geta-optimizely-genericlinks/assets/108930057/7f8fd7b5-7a43-4886-afe0-04627a17d759)

**Comment by svenrog** [comment]
This has been addressed in `v1.6.1` and submitted to https://nuget.optimizely.com/

**Comment by svenrog** [comment]
@adayinthelifeofapro can you update and verify that this is fixed?
