### ISSUE TITLE
Delete button does not trigger autosave, or remove link

### ISSUE THREAD

**Issue by joemayberry-perficient** [Geta/geta-optimizely-genericlinks#20]
We are currently running GenericLinks version 1.6.1 with Optimizely CMS version 12.19.0.

We are seeing an issue where clicking the delete button, either the "DELETE" button on the link properties modal or the 'X' button content reference link, does not trigger an autosave, and does not remove the link.

![delete-link-1](https://github.com/Geta/geta-optimizely-genericlinks/assets/105795917/40350d07-c3ef-4fd2-96c2-57fa875882d2)
![delete-link-2](https://github.com/Geta/geta-optimizely-genericlinks/assets/105795917/f0392c03-57d0-40e1-bab9-baa384f26c91)

Thank you,
Joe Mayberry

**Comment by svenrog** [comment]
This has been addressed in `v1.6.2` and submitted to https://nuget.optimizely.com/

**Comment by svenrog** [comment]
@joemayberry-perficient can you update and verify that this is fixed?

**Comment by joemayberry-perficient** [comment]
@svenrog My apologies for not updating the issue. Yes this issue is fixed. Thank you for the support.
