### ISSUE TITLE
Optimizely Import/export tool not importing Page Links correctly

### ISSUE THREAD

**Issue by madritz** [Geta/geta-optimizely-genericlinks#22]
Hi 
We use GenericLinks for all LinkItem properties in our project. However when we ran the import/export tool, any links pointing to CMS Pages, did not get imported correctly. Please review and let us know if/when this integration will be fixed.

**Comment by svenrog** [comment]
I've addressed this in `1.8.0` and added property transforms for `LinkData` properties. Submitting to https://nuget.optimizely.com/ as soon as CI completes.

There is an extra step that has to be taken for exports to work, documented here:
https://github.com/Geta/geta-optimizely-genericlinks/blob/master/docs/example-link-data-collection.md#register-type-for-importexport.

**Comment by madritz** [comment]
thanks Sven! Waiting for 1.8 release now.

**Comment by valdisiljuconoks** [comment]
check within a few hours. usually it does not take long for the publishing.

**Comment by madritz** [comment]
its resolved. Thanks!
