### ISSUE TITLE
Custom boolean value resets when published

### ISSUE THREAD

**Issue by alex-finnigan-mando** [Geta/geta-optimizely-genericlinks#30]
This issue was previously mentioned in #10 but was closed by the author without commenting. I'm hoping I just need advice on this one.

We have a custom field used to simplify the setting of a URL target:
```c#
[Display(Name = "Open In New Tab")]
public virtual bool OpenInNewTab
{
    get => GetAttribute((v) => bool.Parse(v));
    set => SetAttribute(value, (v) => v.ToString());
}
``` 

However, this property appears to reset to it's unchecked state after the block/page has been published.

See demo: 
[screen-capture.webm](https://github.com/Geta/geta-optimizely-genericlinks/assets/58000135/2f33b73a-76db-487b-873c-729fe762852e)

Please let me know if the code above is wrong or if this is a genuine bug.

Cheers!

**Comment by pamiddleton** [comment]
This may be a little late in terms of a reply but you can achieve this with a ILinkDataValueWriter described here: https://github.com/Geta/geta-optimizely-genericlinks/blob/master/docs/adding-support-for-new-properties.md 
Example: 

```
public class BoolValueWriter : ILinkDataValueWriter
{
    public bool CanWrite(Type type)
    {
        if (typeof(Boolean).IsAssignableFrom(type))
            return true;

        if (typeof(Boolean?).IsAssignableFrom(type))
            return true;

        return false;
    }

    public void Write(Utf8JsonWriter writer, object value)
    {
        var boolValue = (Boolean)value;
        writer.WriteBooleanValue(boolValue);
    }
}
```
