### ISSUE TITLE
Data lost on publishing when updating model

### ISSUE THREAD

**Issue by emarksonopti** [Geta/geta-optimizely-genericlinks#32]
Hello,

I have spoken with @valdisiljuconoks, but wanted to get an official report.

I am using latest: 1.8.3

Model looks like this, before update. everything worked:

public class ExampleLinkData : LinkData
{
    [Display(Name = "GTM Text", Order = 210)]
    public virtual string GTMText { get; set; }
    [Display(Name = "Custom Classes", Order = 230)]
    public virtual string CustomClasses { get; set; }
}

Model was updated to this:

public class ExampleLinkData : LinkData
{
    [Display(Name = "GTM Text", Order = 210)]
    public virtual string GTMText { get; set; }
    [Display(Name = "Custom Text Classes", Order = 220)]
    public virtual string CustomTextClasses { get; set; }
    [Display(Name = "Custom Link Classes", Order = 230)]
    public virtual string CustomClasses { get; set; }
}

-----------------------

I can confirm that Property Definitions are also created for both LinkDataCollection and LinkData.

Import/Export startup method is being called.

-----------------------

After deploying the updates, it seems every custom field (extending on LinkData) gets saved on autosave, BUT when we publish the block, all three of the extended fields get cleared.

Video: https://app.screencast.com/tnXbny8T9ToAm

**Comment by emarksonopti** [comment]
Changing my `get; set;` to use the actual get and set methods, tweaked slightly, from the shown example for a ContentReference made this work immedietly:

[Display(Name = "GTM Text", Order = 210)]
public virtual string GTMText { 
    get => GetAttribute((v) => v); 
    set => SetAttribute(value, (v) => v.ToString()); }

[Display(Name = "Custom Text Classes", Order = 220)]
public virtual string CustomTextClasses {

    get => GetAttribute((v) => v);
    set => SetAttribute(value, (v) => v.ToString());
}

[Display(Name = "Custom Classes", Order = 230)]
public virtual string CustomClasses {
    get => GetAttribute((v) => v);
    set => SetAttribute(value, (v) => v.ToString());
}

**Comment by svenrog** [comment]
I've provided some additional property types in the [documentation](https://github.com/Geta/geta-optimizely-genericlinks/blob/master/docs/example-link-data-collection.md) so that it is clearer that this implementation is required.
