### ISSUE TITLE
How to nest these genericlinks?

### ISSUE THREAD

**Issue by landg-lance** [Geta/geta-optimizely-genericlinks#5]
I'd like to be able to have a genericlink as a property of a genericlink in order to create hierarchies for navigation.  Do you have any suggestions... I notice that the Property Types links https://github.com/Geta/geta-optimizely-genericlinks/blob/master/docs/advanced-property-handling.md#supported-property-types explicitly excludes blocks...

**Comment by svenrog** [comment]
Because of the way this data is persisted, like a link with properties being attributes, makes nesting impossible. There is also the problem of getting the UI to handle nesting. The entire editor would have to be rebuilt from the ground up.
